services:
  nginx:
    depends_on:
      - golang-example
      - nestjs-example
      - react-express-example
    environment:
      - PROXY_DIR=proxy_example
  golang-example:
    build:
      context: ./examples/golang
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - single-deploy
  nestjs-example:
    build:
      context: ./examples/nestjs
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - single-deploy
  react-express-example:
    build:
      context: ./examples/react-express
      dockerfile: Dockerfile
    restart: always
    networks:
      - single-deploy
networks:
  single-deploy:
    driver: bridge
