include:
  - demo.yaml
services:
  nginx:
    depends_on:
      - golang-server
      - nestjs-server
      - nextjs-server
      - react-express
    environment:
      - TZ=Asia/Shanghai
      - PROXY_DIR=proxy_dev
  user-api:
    environment:
      - ENVIRONMENT=development
  user-rpc:
    environment:
      - ENVIRONMENT=development
