services:
  nginx:
    depends_on:
      - golang-example
      - nestjs-example
      - react-express-example
    environment:
      - PROXY_DIR=proxy_example
  golang-example:
    build:
      context: ./examples/golang
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "3500:8888"
    networks:
      - single-deploy
  nestjs-example:
    build:
      context: ./examples/nestjs
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "3501:3000"
    networks:
      - single-deploy
  react-express-example:
    build:
      context: ./examples/react-express
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3502:3002"
    networks:
      - single-deploy
