include:
  - infra.yaml
services:
  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - spiritchess.cn
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Shanghai
      - PROXY_DIR=proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
      - ./nginx/crts:/etc/nginx/crts
      - ./nginx/templates:/etc/nginx/templates
    networks:
      - single-deploy
  spiritchess.cn:
    build:
      context: ./spiritchess.cn
      dockerfile: Dockerfile
    restart: always
    networks:
      - single-deploy
networks:
  single-deploy:
    driver: bridge
