cache:
  host: localhost
  port: 6379
  username: default
  password: single_deploy

db:
  type: mysql
  host: 127.0.0.1
  port: 3306
  database: single_deploy
  username: root
  password: single_deploy
